# Generated by Django 3.1.2 on 2021-04-08 08:18

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=todo.models.Task.default_start_time, null=True),
        ),
    ]
